// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD_7Q0-d1Q5pqj3crF4Mx9pX8JwSDQe64A',
    appId: '1:871144783870:web:8fbdeced8b0757abd98aaf',
    messagingSenderId: '871144783870',
    projectId: 'riverpod-291202',
    authDomain: 'riverpod-291202.firebaseapp.com',
    storageBucket: 'riverpod-291202.firebasestorage.app',
    measurementId: 'G-ZTZNHKZC1T',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA_J9e1QUL0K4jXKFQImiAb6YQ21DK81Eg',
    appId: '1:871144783870:android:22cf2bb61af7b5cbd98aaf',
    messagingSenderId: '871144783870',
    projectId: 'riverpod-291202',
    storageBucket: 'riverpod-291202.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBQbGi5r9xfDyR_S_fNapQ21KsFi10OkA0',
    appId: '1:871144783870:ios:278af51232cdb201d98aaf',
    messagingSenderId: '871144783870',
    projectId: 'riverpod-291202',
    storageBucket: 'riverpod-291202.firebasestorage.app',
    iosBundleId: 'com.example.riverpodMang',
  );
}
